import argparse
import csv
import shutil
import subprocess
import sys
import time
from pathlib import Path


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}


def find_latest_image(directory: Path, since_time: float | None = None) -> Path | None:
    candidates = []
    for p in directory.glob("*"):
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS:
            try:
                mtime = p.stat().st_mtime
            except OSError:
                continue
            if since_time is None or mtime >= since_time:
                candidates.append((mtime, p))

    if not candidates:
        return None

    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


def sanitize_text_for_filename(text: str, max_len: int = 40) -> str:
    keep = []
    for ch in text:
        if ch.isalnum():
            keep.append(ch)
        elif ch in (" ", "-", "_"):
            keep.append("_")
    s = "".join(keep)
    while "__" in s:
        s = s.replace("__", "_")
    s = s.strip("_")
    if len(s) > max_len:
        s = s[:max_len].rstrip("_")
    return s or "prompt"


def run_one_prompt(
    python_exe: str,
    sandbox_root: Path,
    pipeline: str,
    prompt: str,
    extra_args: list[str] | None = None,
) -> subprocess.CompletedProcess:
    cmd = [
        python_exe,
        str(sandbox_root / "scripts" / "run_pipelines.py"),
        "--pipelines",
        pipeline,
        "--prompt",
        prompt,
    ]

    if extra_args:
        cmd.extend(extra_args)

    print("Running:", " ".join(f'"{x}"' if " " in x else x for x in cmd))
    return subprocess.run(cmd, cwd=sandbox_root, check=True)


def main():
    parser = argparse.ArgumentParser(
        description="Run SD sandbox inference from prompt CSV."
    )
    parser.add_argument(
        "--csv",
        required=True,
        help="Input CSV generated by generate_people_prompts.py",
    )
    parser.add_argument(
        "--pipeline",
        default="sdxl_base",
        help="Pipeline name (default: sdxl_base)",
    )
    parser.add_argument(
        "--sandbox_root",
        default=".",
        help="Root directory of sd-sandbox (default: current directory)",
    )
    parser.add_argument(
        "--generated_dir",
        default="test/generated_images",
        help="Generated images directory inside sd-sandbox",
    )
    parser.add_argument(
        "--output_dir",
        default="dataset_out",
        help="Where renamed dataset images are saved",
    )
    parser.add_argument(
        "--metadata_name",
        default="metadata.csv",
        help="Output metadata CSV filename",
    )
    parser.add_argument(
        "--start_id",
        type=int,
        default=1,
        help="Start from this prompt id (inclusive)",
    )
    parser.add_argument(
        "--end_id",
        type=int,
        default=1000000,
        help="End at this prompt id (inclusive)",
    )
    parser.add_argument(
        "--sleep_sec",
        type=float,
        default=1.0,
        help="Sleep seconds between runs",
    )
    parser.add_argument(
        "--benchmark",
        action="store_true",
        help="Pass --benchmark to run_pipelines.py",
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Only print what would be executed",
    )
    args = parser.parse_args()

    sandbox_root = Path(args.sandbox_root).resolve()
    csv_path = Path(args.csv).resolve()
    generated_dir = (sandbox_root / args.generated_dir).resolve()
    output_dir = (sandbox_root / args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    metadata_path = output_dir / args.metadata_name

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    if not generated_dir.exists():
        raise FileNotFoundError(f"Generated image dir not found: {generated_dir}")

    python_exe = sys.executable

    extra_args = []
    if args.benchmark:
        extra_args.append("--benchmark")

    rows = []
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    metadata_rows = []

    for row in rows:
        try:
            prompt_id = int(row["id"])
        except Exception:
            print(f"[WARN] skip row with invalid id: {row}")
            continue

        if prompt_id < args.start_id or prompt_id > args.end_id:
            continue

        prompt = row["prompt"]
        num_people = row.get("num_people", "")
        location = row.get("location", "")
        time_of_day = row.get("time_of_day", "")
        situation = row.get("situation", "")

        short_tag = sanitize_text_for_filename(location or situation, max_len=24)
        out_name = f"img_{prompt_id:03d}_p{int(num_people):02d}_{short_tag}.png"
        out_path = output_dir / out_name

        print("=" * 80)
        print(f"[{prompt_id:03d}] people={num_people}")
        print(prompt)

        if args.dry_run:
            continue

        t0 = time.time()

        before_latest = find_latest_image(generated_dir)

        run_one_prompt(
            python_exe=python_exe,
            sandbox_root=sandbox_root,
            pipeline=args.pipeline,
            prompt=prompt,
            extra_args=extra_args,
        )

        time.sleep(1.0)

        latest = find_latest_image(generated_dir, since_time=t0)

        if latest is None:
            latest = find_latest_image(generated_dir)

        if latest is None:
            print(f"[ERROR] No generated image found for id={prompt_id}")
            continue

        shutil.copy2(latest, out_path)
        print(f"[OK] copied: {latest.name} -> {out_path}")

        metadata_rows.append(
            {
                "id": prompt_id,
                "num_people": num_people,
                "pipeline": args.pipeline,
                "output_image": out_name,
                "source_generated_image": latest.name,
                "location": location,
                "time_of_day": time_of_day,
                "situation": situation,
                "prompt": prompt,
            }
        )

        with metadata_path.open("w", encoding="utf-8-sig", newline="") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "id",
                    "num_people",
                    "pipeline",
                    "output_image",
                    "source_generated_image",
                    "location",
                    "time_of_day",
                    "situation",
                    "prompt",
                ],
            )
            writer.writeheader()
            writer.writerows(metadata_rows)

        time.sleep(args.sleep_sec)

    print("\nDone.")
    print(f"Output dir : {output_dir}")
    print(f"Metadata   : {metadata_path}")


if __name__ == "__main__":
    main()